### ISSUE TITLE
Permissions denied /tmp

### ISSUE THREAD

**Issue by Savanta** [smartgic/docker-mycroft#32]
I'm trying to deploy mycroft via Portainer
Here's mycroft_skills log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mycroft/core/mycroft/skills/__main__.py", line 295, in <module>
  File "/home/mycroft/core/mycroft/skills/__main__.py", line 200, in main
  File "/home/mycroft/core/mycroft/lock/__init__.py", line 119, in __init__
    mycroft.lock.Lock('skills')
  File "/home/mycroft/core/mycroft/lock/__init__.py", line 173, in create
    self.create()
    self.touch()
  File "/home/mycroft/core/mycroft/lock/__init__.py", line 160, in touch
    with open(self.path, 'w') as L:
PermissionError: [Errno 13] Permission denied: '/tmp/mycroft/skills.pid'
```
My .env file:
```
CONFIG_FOLDER=/media/Dane/.docker/mycroft/mycroft-config
WEBCACHE_FOLDER=/media/Dane/.docker/mycroft/mycroft-web-cache
MODELS_FOLDER=/media/Dane/.docker/mycroft/mycroft-precise-models
CACHE_FOLDER=/media/Dane/.docker/mycroft/mycroft-cache
MIMIC3_VOICES_FOLDER=/media/Dane/.docker/mycroft/mycroft-mimic3-voices
COMPOSE_HTTP_TIMEOUT=120
VERSION=latest
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=~/.docker.xauth
X11_SOCKET=/tmp/.X11-unix
```
Files in /media/Dane/.docker/mycroft are created [fine](http://0x0.st/oF9m.jpg)

**Comment by goldyfruit** [comment]
Could you please check the permission of `/tmp/mycroft`  directory inside the `mycroft_skills` container?

**Comment by goldyfruit** [comment]
Ok, just saw your screenshot, the directory you created belongs to `root` when they should belong to user with UID `1000`.

Here is an extract of the `README`

```
$ mkdir mycroft-config mycroft-web-cache mycroft-precise-models mycroft-cache mycroft-mimic3-voices
$ chown 1000:1000 mycroft-config mycroft-web-cache mycroft-precise-models mycroft-cache mycroft-mimic3-voices
```

**Comment by Savanta** [comment]
Problem solved, thanks
